Repository jdtoombs/RustyBot, pull requests merged in 2021-05, with the labels that each got.

#4 Adding rustplus-api as a dependency
  .github/CODEOWNERS
  package-lock.json
  package.json
  src/main.ts
  tsconfig.json
  types/rustplus-api/index.d.ts
Labels: enhancement

#5 Introduce ES6 Class
  .env.example
  package-lock.json
  package.json
  src/client.ts
  src/commands/echo.ts
  src/handlers/CommandHandler.ts
  src/main.ts
  src/utils/interfaces.ts
  src/utils/logger.ts
  tsconfig.json
Labels: enhancement

#6 Quick integration with rustplus
  src/rust.ts
Labels: enhancement

#7 command/event handlers
  package-lock.json
  package.json
  src/client.ts
  src/commands/echo.ts
  src/events/message.ts
  src/handlers/CommandHandler.ts
  src/handlers/EventHandler.ts
Labels: enhancement

#9 Start to dockerize 🐳
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: tech enhancement

#12 Add form of testing to our project 🧪
  jest.config.js
  package-lock.json
  package.json
  tests/sample.test.ts
Labels: tests
